INSERT INTO users (name, age) VALUES ("Stacy Grant", 34);
INSERT INTO users (name, age) VALUES ("Terrence Walker", 29);
INSERT INTO users (name, age) VALUES ("Shanae Robinson", 24);
INSERT INTO users (name, age) VALUES ("Joy Coe", 51);
INSERT INTO users (name, age) VALUES ("Micha Harrit", 50);
INSERT INTO users (name, age) VALUES ("Lebron James", 55);
INSERT INTO users (name, age) VALUES ("Michael Jones", 49);
INSERT INTO users (name, age) VALUES ("Shirley Tomas", 45);
INSERT INTO users (name, age) VALUES ("Lily Flowers", 38);
INSERT INTO users (name, age) VALUES ("Shar Jackson", 84);
INSERT INTO users (name, age) VALUES ("Beatrice Wilkins", 57);
INSERT INTO users (name, age) VALUES ("Ernest Grant", 33);
INSERT INTO users (name, age) VALUES ("Nicole Ray", 27);
INSERT INTO users (name, age) VALUES ("Coby Bryant", 26);
INSERT INTO users (name, age) VALUES ("Pierre Smith", 27);
INSERT INTO users (name, age) VALUES ("Oprah Jones", 26);
INSERT INTO users (name, age) VALUES ("Tiffany Wilson", 21);
INSERT INTO users (name, age) VALUES ("Amy Utopia", 32);
INSERT INTO users (name, age) VALUES ("Z Drake", 18);
INSERT INTO users (name, age) VALUES ("Natasha Brews", 26);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Joy of Styling", "Fashion Consultant", 600, "5/1/20", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Black Girl's Code", "Technology", 1000, "5/1/17", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Clean it Like you Mean it", "Environmental", 625, "5/1/20", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("March of Dimes", "Health", 500, "5/1/20", "6/30/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Lose the Gut, Keep the Butt", "Fitness", 600, "5/1/20", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bridges", "Mental Health", 275, "5/1/20", "7/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sole Haircare", "Cosmetics", 1060, "5/1/20", "5/1/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fibroid Awareness", "Womens Health", 400, "5/1/20", "7/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Check Mate", "Dating" , 1000, "5/1/20", "7/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Soup Kitchen", "Non Profit", 250, "6/1/20", "7/31/20");

INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);